stages:
 - lint

# common for all jobs in all stages
.stage-default: &stage-default
  only:
    - master
    - merge_requests

code-style-check:
 stage: lint
 script:
    # Install eslint
    - |
      npm i eslint@^8.0.1 \
      eslint-config-standard@latest \
      eslint-plugin-import@^2.25.2 \
      eslint-plugin-n@^15.0.0 || ^16.0.0  \
      eslint-plugin-promise@^6.0.0

    # Run eslint
    - node_modules/eslint/bin/eslint.js -c ./cicd/.eslintrc.js 'functions/**/*.js'
 <<: *stage-default
